market_posgres: "postgres://cargos:!woaini521@localhost/cargos"
indexer_db_posgres: "postgres://postgres:!Woaini521@localhost/postgres"
work_number: 16
key: "AKIAT7L2KGCBRVYWHAOG"
secret: "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"
